// Generated by Style Dictionary
import '../css/tokens.css';
import '../css/modes.css';
import '../css/themes/glass.css';
import '../css/themes/brutal.css';
import '../css/themes/neumorph.css';
import '../css/themes/neobrutal.css';
import '../css/themes/minimal.css';
import '../css/themes/futuristic.css';
import '../css/themes/bento.css';

// Your authored SCSS (utilities, reset, typography)
import '../scss/main.scss';

// Import all Web Components to register them with the browser
import '../components/crusher-button.js';
import '../components/crusher-card.js';
import '../components/crusher-timeline.js';
import '../components/crusher-timeline-item.js';
import '../components/crusher-input.js';
import '../components/crusher-modal.js';
import '../components/crusher-textarea.js';
import '../components/crusher-skill-bar.js';
import '../components/crusher-section-title.js';
import '../components/crusher-style-switcher.js';

console.log("Crusher UI Kit components loaded!");