name: Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  version_or_pr:
    name: Changesets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          registry-url: https://registry.npmjs.org

      - run: npm ci

      - name: Build tokens
        run: npm run build:tokens

      - name: Check contrast
        run: npm run check:contrast

      - name: Build lib
        run: npm run build

      - name: Create Release PR or Publish
        uses: changesets/action@v1
        with:
          version: npx changeset version
          publish: npm publish --provenance --access public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
